package net.astronomy.multilib.core.devtool;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.minecraft.resources.ResourceLocation;

import java.util.List;
import java.util.Map;

/**
 * Turns a {@link MultiblockScanResult} into the three static-geometry export formats the dev block
 * offers: a Java scaffold, a KubeJS script, and a datapack JSON definition. Every format shares the
 * exact same intermediate representation (the scan result) - this class never re-derives layers or
 * symbols itself, it only serializes what {@link MultiblockScanner} already computed.
 *
 * <p>None of the three formats capture behavioral features (formation mode, validators, callbacks,
 * shell/interior, auto-place, etc.) - only the static geometry (layers, keys, core/activation). See
 * {@code roadmap/phase-10-dev-authoring-tool.md} for the full scope rationale; each generated output
 * carries an explicit {@code TODO} comment saying so.
 */
public final class MultiblockDevExporter {

    private MultiblockDevExporter() {}

    /** {@code "fusion_reactor"} -> {@code "MultiblockFusionReactor"}. */
    public static String javaClassName(String path) {
        StringBuilder sb = new StringBuilder("Multiblock");
        boolean capitalizeNext = true;
        for (int i = 0; i < path.length(); i++) {
            char c = path.charAt(i);
            if (c == '_' || c == '.' || c == '-' || c == '/') {
                capitalizeNext = true;
                continue;
            }
            sb.append(capitalizeNext ? Character.toUpperCase(c) : c);
            capitalizeNext = false;
        }
        return sb.toString();
    }

    public static String toJavaSource(String namespace, String path, MultiblockScanResult scan, String variantName) {
        String className = javaClassName(path);

        StringBuilder sb = new StringBuilder();
        // First line only: read back by MultiblockDevOutputPaths.readExistingExportId to detect whether
        // re-exporting under this path would clobber a *different* multiblock's file (the file name
        // is path-only, so two different multiblocks sharing a path but a different namespace would
        // otherwise silently overwrite each other).
        sb.append(MultiblockDevOutputPaths.EXPORT_ID_MARKER_PREFIX).append(namespace).append(':').append(path).append('\n');
        sb.append("// TODO: replace com.example.yourmod with your own mod's package.\n");
        sb.append("package com.example.yourmod;\n\n");
        sb.append("import net.astronomy.multilib.api.MultiLib;\n");
        sb.append("import net.minecraft.core.registries.BuiltInRegistries;\n");
        sb.append("import net.minecraft.resources.ResourceLocation;\n\n");
        sb.append("// TODO: substitute the BuiltInRegistries lookups below with your own static Block fields where available.\n");
        sb.append("// Scaffold generated by the Multiblock Dev Block - fill in formationMode/validator/callbacks/etc. by hand.\n");
        sb.append("public final class ").append(className).append(" {\n");
        sb.append("    public static void register() {\n");
        sb.append("        MultiLib.define(ResourceLocation.fromNamespaceAndPath(\"")
                .append(namespace).append("\", \"").append(path).append("\"))\n");

        boolean variant = variantName != null && !variantName.isBlank();
        String bodyIndent = variant ? "                " : "            ";
        if (variant) {
            sb.append("            .variant(\"").append(variantName).append("\", v -> v\n");
        }

        for (List<String> layer : scan.layers()) {
            sb.append(bodyIndent).append(".layer(");
            appendJavaStringArgs(sb, layer);
            sb.append(")\n");
        }

        for (Map.Entry<Character, ResourceLocation> entry : scan.symbolToBlock().entrySet()) {
            sb.append(bodyIndent).append(".key('").append(entry.getKey()).append("', BuiltInRegistries.BLOCK.get(ResourceLocation.parse(\"")
                    .append(entry.getValue()).append("\")))\n");
        }

        if (variant) {
            sb.append("            )\n");
        }

        appendCoreOrActivationLineJava(sb, scan);

        sb.append("            .build();\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    public static String toKubeJsScript(String namespace, String path, MultiblockScanResult scan, String variantName) {
        StringBuilder sb = new StringBuilder();
        sb.append(MultiblockDevOutputPaths.EXPORT_ID_MARKER_PREFIX).append(namespace).append(':').append(path).append('\n');
        sb.append("// server_scripts/<kubejs folder>/").append(path).append(".js\n");
        sb.append("// Scaffold generated by the Multiblock Dev Block - fill in formationMode/validator/callbacks/etc. by hand.\n");
        sb.append("MultiblockEvents.create(event => {\n");
        sb.append("    event.multiblock('").append(namespace).append(':').append(path).append("')\n");

        boolean variant = variantName != null && !variantName.isBlank();
        String bodyIndent = variant ? "            " : "        ";
        if (variant) {
            sb.append("        .variant('").append(variantName).append("', v => v\n");
        }

        for (List<String> layer : scan.layers()) {
            sb.append(bodyIndent).append(".layer(");
            appendJsStringArgs(sb, layer);
            sb.append(")\n");
        }

        // MultiblockUtils.block(...) instead of a bare string literal: MultiblockBuilder#key has both a
        // String overload and a Block overload, and KubeJS/Rhino registers an implicit string->Block
        // coercion, so a plain string argument makes the two overloads genuinely ambiguous to Rhino at
        // call time ("Error in 'MultiblockEvents.create': ... choice of Java method ... key matching
        // JavaScript argument types (string,string) is ambiguous") - every generated script failed to
        // load. Wrapping the id in MultiblockUtils.block(...) first means the second argument is already
        // a BlockIngredient by the time .key(...) runs, which only has one 2-arg overload accepting it.
        // A fully-qualified net.astronomy.multilib....BlockIngredient.parse(...) call was tried first and
        // doesn't work at all - KubeJS's sandboxed Rhino doesn't expose bare top-level Java package names
        // as globals, so that threw "ReferenceError: net is not defined" instead. MultiblockUtils is
        // already a registered global KubeJS binding (see MultiLibKubeJSPlugin), so no such reference is
        // needed.
        for (Map.Entry<Character, ResourceLocation> entry : scan.symbolToBlock().entrySet()) {
            sb.append(bodyIndent).append(".key('").append(entry.getKey())
                    .append("', MultiblockUtils.block('")
                    .append(entry.getValue()).append("'))\n");
        }

        if (variant) {
            sb.append("        )\n");
        }

        appendCoreOrActivationLineJs(sb, scan);

        sb.append("})\n");
        return sb.toString();
    }

    public static String toJsonDefinition(String namespace, String path, MultiblockScanResult scan, String variantName) {
        JsonObject root = new JsonObject();
        // Not read by the real datapack loader (MultiblockJsonLoader ignores unknown keys) - purely for
        // MultiblockDevOutputPaths#readExistingExportId (path/file-collision detection, JSON has no
        // comment syntax to embed a marker line in like Java/KubeJS do) and MultiblockDevExportLoader (to
        // recover the multiblock's full id, since the file itself is named after the path alone -
        // namespace is CommonConfig.DEVTOOL_NAMESPACE, fixed and shared by every export, so it never differs).
        root.addProperty("id", namespace + ":" + path);

        JsonArray layersArr = new JsonArray();
        for (List<String> layer : scan.layers()) {
            JsonArray layerArr = new JsonArray();
            for (String row : layer) {
                layerArr.add(row);
            }
            layersArr.add(layerArr);
        }

        boolean variant = variantName != null && !variantName.isBlank();
        if (variant) {
            // Keys/core/activation stay top-level (shared) - see MultiblockJsonLoader#parseDefinition,
            // which only forbids top-level "layers" alongside "variants", not "keys"/"core"/"activation".
            // The dev tool only ever exports one geometry at a time, so this is always a lone variant
            // entry - legal (if pointless standalone) per MultiblockBuilder#variant's own javadoc; the
            // natural way to hand-assemble a multi-variant definition is exporting each variant under the
            // same path and merging the "variants" arrays by hand afterward.
            JsonObject variantObj = new JsonObject();
            variantObj.addProperty("name", variantName);
            variantObj.add("layers", layersArr);
            JsonArray variantsArr = new JsonArray();
            variantsArr.add(variantObj);
            root.add("variants", variantsArr);
        } else {
            root.add("layers", layersArr);
        }

        JsonObject keys = new JsonObject();
        for (Map.Entry<Character, ResourceLocation> entry : scan.symbolToBlock().entrySet()) {
            JsonObject blockObj = new JsonObject();
            blockObj.addProperty("block", entry.getValue().toString());
            keys.add(String.valueOf(entry.getKey()), blockObj);
        }
        root.add("keys", keys);

        // "activation" is only written when there's no core - a JSON multiblock with a core doesn't need
        // a separate activation symbol at all (the multiblock format already treats core as usable for
        // activation too), so forcing an identical "activation" alongside "core" was redundant, not a
        // second piece of information.
        if (scan.coreSymbol() != null) {
            root.addProperty("core", String.valueOf(scan.coreSymbol()));
        } else if (scan.activationSymbol() != null) {
            root.addProperty("activation", String.valueOf(scan.activationSymbol()));
        }

        return new GsonBuilder().setPrettyPrinting().create().toJson(root);
    }

    private static void appendCoreOrActivationLineJava(StringBuilder sb, MultiblockScanResult scan) {
        if (scan.coreSymbol() != null) {
            sb.append("            .core('").append(scan.coreSymbol()).append("')\n");
        } else if (scan.activationSymbol() != null) {
            sb.append("            .activation('").append(scan.activationSymbol()).append("')\n");
        } else {
            sb.append("            // TODO: no core/activation was tagged, add one by hand.\n");
        }
    }

    private static void appendCoreOrActivationLineJs(StringBuilder sb, MultiblockScanResult scan) {
        if (scan.coreSymbol() != null) {
            sb.append("        .core('").append(scan.coreSymbol()).append("')\n");
        } else if (scan.activationSymbol() != null) {
            sb.append("        .activation('").append(scan.activationSymbol()).append("')\n");
        } else {
            sb.append("        // TODO: no core/activation was tagged, add one by hand.\n");
        }
    }

    private static void appendJavaStringArgs(StringBuilder sb, List<String> rows) {
        for (int i = 0; i < rows.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append('"').append(escapeJava(rows.get(i))).append('"');
        }
    }

    private static void appendJsStringArgs(StringBuilder sb, List<String> rows) {
        for (int i = 0; i < rows.size(); i++) {
            if (i > 0) sb.append(", ");
            sb.append('\'').append(escapeJs(rows.get(i))).append('\'');
        }
    }

    private static String escapeJava(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }

    private static String escapeJs(String s) {
        return s.replace("\\", "\\\\").replace("'", "\\'");
    }

    /**
     * The actual player-visible text a lang entry for this multiblock should map to: the Display Name
     * field exactly as typed, or the path itself as a fallback when it was left blank - path (not
     * namespace) because it's the per-multiblock unique GUI field, so the fallback still tells two
     * un-named multiblocks apart, unlike namespace which is the same fixed value for every export. Never
     * part of the translation key itself (that's always {@code multiblock.<namespace>.<path>} - see
     * {@link #toJavaSource}'s own comment) - only ever this value.
     */
    public static String resolveDisplayText(String path, String displayName) {
        return (displayName == null || displayName.isBlank()) ? path : displayName.trim();
    }
}
